import type { Metadata } from "next";
import StyledComponentsRegistry from "../lib/registry";
import { BodyWrapper } from "../styling/shared_styles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <BodyWrapper>
        <StyledComponentsRegistry> {children} </StyledComponentsRegistry>
      </BodyWrapper>
    </html>
  );
}
