import type { Metadata } from "next";
import StyledComponentsRegistry from "../lib/registry";
import { BodyWrapper } from "../styling/shared_styles";
import { Inconsolata, Raleway, Roboto_Slab } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inconsolata = Inconsolata({
  weight: ["600", "700", "900"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});
const raleway = Raleway({
  weight: ["100", "300", "400", "500", "600", "800"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

const robotoSlab = Roboto_Slab({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={raleway.className}>
      <BodyWrapper>
        <StyledComponentsRegistry> {children} </StyledComponentsRegistry>
      </BodyWrapper>
    </html>
  );
}
